services:
  - type: web
    name: linklite-backend
    env: node
    plan: free
    healthCheckPath: /
    buildFilter:
      paths:
      - backend/**
    envVars:
      - key: DB_USER
        fromDatabase:
          name: linklite-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: linklite-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: linklite-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: linklite-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: linklite-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: DOMAIN
        fromService:
          type: web
          name: linklite-backend
          property: url
      - key: NODE_ENV
        value: production
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"

  - type: web
    name: linklite-frontend
    plan: free
    env: static
    staticPublishPath: ./frontend
    buildFilter:
      paths:
      - frontend/**

databases:
  - name: linklite-db
    plan: free
    databaseName: linklite
    user: linklite
    postgresMajorVersion: 14
